# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'evolution_combined_ui.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.parent_image = QLabel(self.centralwidget)
        self.parent_image.setObjectName(u"parent_image")
        self.parent_image.setGeometry(QRect(200, 250, 250, 250))
        self.parent_image.setPixmap(QPixmap(u"../../resources/question_mark.png"))
        self.parent_image.setScaledContents(True)
        self.mate_label = QLabel(self.centralwidget)
        self.mate_label.setObjectName(u"mate_label")
        self.mate_label.setGeometry(QRect(800, 25, 251, 51))
        font = QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.mate_label.setFont(font)
        self.mate_label.setAlignment(Qt.AlignCenter)
        self.candidate_1_button = QPushButton(self.centralwidget)
        self.candidate_1_button.setObjectName(u"candidate_1_button")
        self.candidate_1_button.setGeometry(QRect(850, 90, 175, 175))
        self.candidate_1_button.setAutoFillBackground(False)
        icon = QIcon()
        icon.addFile(u"../../resources/question_mark.png", QSize(), QIcon.Normal, QIcon.Off)
        self.candidate_1_button.setIcon(icon)
        self.candidate_1_button.setIconSize(QSize(175, 175))
        self.candidate_3_button = QPushButton(self.centralwidget)
        self.candidate_3_button.setObjectName(u"candidate_3_button")
        self.candidate_3_button.setGeometry(QRect(850, 490, 175, 175))
        self.candidate_3_button.setIcon(icon)
        self.candidate_3_button.setIconSize(QSize(175, 175))
        self.parent_label = QLabel(self.centralwidget)
        self.parent_label.setObjectName(u"parent_label")
        self.parent_label.setGeometry(QRect(200, 195, 251, 51))
        font1 = QFont()
        font1.setPointSize(24)
        font1.setBold(True)
        font1.setWeight(75)
        self.parent_label.setFont(font1)
        self.parent_label.setAlignment(Qt.AlignCenter)
        self.candidate_2_button = QPushButton(self.centralwidget)
        self.candidate_2_button.setObjectName(u"candidate_2_button")
        self.candidate_2_button.setGeometry(QRect(850, 290, 175, 175))
        self.candidate_2_button.setIcon(icon)
        self.candidate_2_button.setIconSize(QSize(175, 175))
        self.child_image = QLabel(self.centralwidget)
        self.child_image.setObjectName(u"child_image")
        self.child_image.setEnabled(True)
        self.child_image.setGeometry(QRect(575, 400, 250, 250))
        self.child_image.setPixmap(QPixmap(u"../../resources/question_mark.png"))
        self.child_image.setScaledContents(True)
        self.parent_1_image = QLabel(self.centralwidget)
        self.parent_1_image.setObjectName(u"parent_1_image")
        self.parent_1_image.setEnabled(True)
        self.parent_1_image.setGeometry(QRect(350, 100, 250, 250))
        self.parent_1_image.setPixmap(QPixmap(u"../../resources/question_mark.png"))
        self.parent_1_image.setScaledContents(True)
        self.parent_1_label = QLabel(self.centralwidget)
        self.parent_1_label.setObjectName(u"parent_1_label")
        self.parent_1_label.setEnabled(True)
        self.parent_1_label.setGeometry(QRect(350, 50, 251, 51))
        self.parent_1_label.setFont(font)
        self.parent_1_label.setAlignment(Qt.AlignCenter)
        self.parent_2_label = QLabel(self.centralwidget)
        self.parent_2_label.setObjectName(u"parent_2_label")
        self.parent_2_label.setEnabled(True)
        self.parent_2_label.setGeometry(QRect(800, 50, 251, 51))
        self.parent_2_label.setFont(font)
        self.parent_2_label.setAlignment(Qt.AlignCenter)
        self.parent_arrows = QLabel(self.centralwidget)
        self.parent_arrows.setObjectName(u"parent_arrows")
        self.parent_arrows.setEnabled(True)
        self.parent_arrows.setGeometry(QRect(460, 110, 481, 381))
        self.parent_arrows.setPixmap(QPixmap(u"../../resources/arrows_merging.png"))
        self.parent_arrows.setScaledContents(True)
        self.parent_2_image = QLabel(self.centralwidget)
        self.parent_2_image.setObjectName(u"parent_2_image")
        self.parent_2_image.setEnabled(True)
        self.parent_2_image.setGeometry(QRect(800, 100, 250, 250))
        self.parent_2_image.setPixmap(QPixmap(u"../../resources/question_mark.png"))
        self.parent_2_image.setScaledContents(True)
        self.loading_animation = QLabel(self.centralwidget)
        self.loading_animation.setObjectName(u"loading_animation")
        self.loading_animation.setEnabled(True)
        self.loading_animation.setGeometry(QRect(530, 250, 250, 250))
        self.loading_animation.setPixmap(QPixmap(u"../../resources/question_mark.png"))
        self.loading_animation.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.parent_arrows.raise_()
        self.parent_image.raise_()
        self.mate_label.raise_()
        self.candidate_1_button.raise_()
        self.candidate_3_button.raise_()
        self.parent_label.raise_()
        self.candidate_2_button.raise_()
        self.child_image.raise_()
        self.parent_1_image.raise_()
        self.parent_1_label.raise_()
        self.parent_2_label.raise_()
        self.parent_2_image.raise_()
        self.loading_animation.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.parent_image.setText("")
        self.mate_label.setText(QCoreApplication.translate("MainWindow", u"Choose a mate", None))
        self.candidate_1_button.setText("")
        self.candidate_3_button.setText("")
        self.parent_label.setText(QCoreApplication.translate("MainWindow", u"Current parent", None))
        self.candidate_2_button.setText("")
        self.child_image.setText("")
        self.parent_1_image.setText("")
        self.parent_1_label.setText(QCoreApplication.translate("MainWindow", u"Current parent", None))
        self.parent_2_label.setText(QCoreApplication.translate("MainWindow", u"Choosen mate", None))
        self.parent_arrows.setText("")
        self.parent_2_image.setText("")
        self.loading_animation.setText("")
    # retranslateUi

