# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'evolution_ui.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_EvolutionGUI(object):
    def setupUi(self, EvolutionGUI):
        if EvolutionGUI.objectName():
            EvolutionGUI.setObjectName(u"EvolutionGUI")
        EvolutionGUI.resize(1280, 720)
        self.centralwidget = QWidget(EvolutionGUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.parent_image_1 = QLabel(self.centralwidget)
        self.parent_image_1.setObjectName(u"parent_image_1")
        self.parent_image_1.setGeometry(QRect(50, 125, 150, 150))
        self.parent_image_1.setPixmap(QPixmap(u"../../../resources/question_mark.png"))
        self.parent_image_1.setScaledContents(True)
        self.parent_image_2 = QLabel(self.centralwidget)
        self.parent_image_2.setObjectName(u"parent_image_2")
        self.parent_image_2.setGeometry(QRect(300, 125, 150, 150))
        self.parent_image_2.setPixmap(QPixmap(u"../../../resources/question_mark.png"))
        self.parent_image_2.setScaledContents(True)
        self.child_image = QLabel(self.centralwidget)
        self.child_image.setObjectName(u"child_image")
        self.child_image.setGeometry(QRect(173, 320, 150, 150))
        self.child_image.setPixmap(QPixmap(u"../../../resources/question_mark.png"))
        self.child_image.setScaledContents(True)
        self.history_image_1 = QLabel(self.centralwidget)
        self.history_image_1.setObjectName(u"history_image_1")
        self.history_image_1.setGeometry(QRect(1080, 125, 150, 150))
        self.history_image_1.setPixmap(QPixmap(u"../../../resources/question_mark.png"))
        self.history_image_1.setScaledContents(True)
        self.history_image_2 = QLabel(self.centralwidget)
        self.history_image_2.setObjectName(u"history_image_2")
        self.history_image_2.setGeometry(QRect(1080, 325, 150, 150))
        self.history_image_2.setPixmap(QPixmap(u"../../../resources/question_mark.png"))
        self.history_image_2.setScaledContents(True)
        self.history_image_3 = QLabel(self.centralwidget)
        self.history_image_3.setObjectName(u"history_image_3")
        self.history_image_3.setGeometry(QRect(1080, 525, 150, 150))
        self.history_image_3.setPixmap(QPixmap(u"../../../resources/question_mark.png"))
        self.history_image_3.setScaledContents(True)
        self.candidate_box = QGroupBox(self.centralwidget)
        self.candidate_box.setObjectName(u"candidate_box")
        self.candidate_box.setGeometry(QRect(530, 70, 450, 450))
        self.candidate_label = QLabel(self.candidate_box)
        self.candidate_label.setObjectName(u"candidate_label")
        self.candidate_label.setGeometry(QRect(75, 200, 300, 50))
        font = QFont()
        font.setPointSize(20)
        self.candidate_label.setFont(font)
        self.candidate_label.setAlignment(Qt.AlignCenter)
        self.candidate_button_1 = QPushButton(self.candidate_box)
        self.candidate_button_1.setObjectName(u"candidate_button_1")
        self.candidate_button_1.setGeometry(QRect(10, 10, 200, 200))
        icon = QIcon()
        icon.addFile(u"../../resources/question_mark.png", QSize(), QIcon.Normal, QIcon.Off)
        self.candidate_button_1.setIcon(icon)
        self.candidate_button_1.setIconSize(QSize(200, 200))
        self.candidate_button_2 = QPushButton(self.candidate_box)
        self.candidate_button_2.setObjectName(u"candidate_button_2")
        self.candidate_button_2.setGeometry(QRect(240, 10, 200, 200))
        self.candidate_button_2.setIcon(icon)
        self.candidate_button_2.setIconSize(QSize(200, 200))
        self.candidate_button_3 = QPushButton(self.candidate_box)
        self.candidate_button_3.setObjectName(u"candidate_button_3")
        self.candidate_button_3.setGeometry(QRect(10, 240, 200, 200))
        self.candidate_button_3.setIcon(icon)
        self.candidate_button_3.setIconSize(QSize(200, 200))
        self.candidate_button_4 = QPushButton(self.candidate_box)
        self.candidate_button_4.setObjectName(u"candidate_button_4")
        self.candidate_button_4.setGeometry(QRect(240, 240, 200, 200))
        self.candidate_button_4.setIcon(icon)
        self.candidate_button_4.setIconSize(QSize(200, 200))
        self.separator = QFrame(self.centralwidget)
        self.separator.setObjectName(u"separator")
        self.separator.setGeometry(QRect(1020, 0, 20, 720))
        self.separator.setFrameShadow(QFrame.Plain)
        self.separator.setLineWidth(3)
        self.separator.setFrameShape(QFrame.VLine)
        self.parent_arrows = QLabel(self.centralwidget)
        self.parent_arrows.setObjectName(u"parent_arrows")
        self.parent_arrows.setGeometry(QRect(124, 134, 250, 251))
        self.parent_arrows.setPixmap(QPixmap(u"../../../resources/arrows_merging.png"))
        self.parent_arrows.setScaledContents(True)
        self.history_label = QLabel(self.centralwidget)
        self.history_label.setObjectName(u"history_label")
        self.history_label.setGeometry(QRect(1060, 50, 200, 50))
        font1 = QFont()
        font1.setPointSize(24)
        self.history_label.setFont(font1)
        self.history_label.setAlignment(Qt.AlignCenter)
        self.tree_label = QLabel(self.centralwidget)
        self.tree_label.setObjectName(u"tree_label")
        self.tree_label.setGeometry(QRect(125, 50, 250, 50))
        self.tree_label.setFont(font1)
        self.tree_label.setAlignment(Qt.AlignCenter)
        self.new_parent = QLabel(self.centralwidget)
        self.new_parent.setObjectName(u"new_parent")
        self.new_parent.setGeometry(QRect(351, 530, 150, 150))
        self.new_parent.setPixmap(QPixmap(u"../../../resources/question_mark.png"))
        self.new_parent.setScaledContents(True)
        self.history_arrow_2 = QLabel(self.centralwidget)
        self.history_arrow_2.setObjectName(u"history_arrow_2")
        self.history_arrow_2.setGeometry(QRect(1120, 475, 70, 50))
        self.history_arrow_2.setPixmap(QPixmap(u"../../../resources/arrow_down.png"))
        self.history_arrow_2.setScaledContents(True)
        self.history_arrow_1 = QLabel(self.centralwidget)
        self.history_arrow_1.setObjectName(u"history_arrow_1")
        self.history_arrow_1.setGeometry(QRect(1120, 275, 70, 50))
        self.history_arrow_1.setPixmap(QPixmap(u"../../../resources/arrow_down.png"))
        self.history_arrow_1.setScaledContents(True)
        self.parent_arrows_2 = QLabel(self.centralwidget)
        self.parent_arrows_2.setObjectName(u"parent_arrows_2")
        self.parent_arrows_2.setGeometry(QRect(320, 410, 211, 121))
        self.parent_arrows_2.setPixmap(QPixmap(u"../../../resources/arrows_merging_2.png"))
        self.parent_arrows_2.setScaledContents(True)
        EvolutionGUI.setCentralWidget(self.centralwidget)
        self.parent_arrows.raise_()
        self.parent_image_1.raise_()
        self.parent_image_2.raise_()
        self.child_image.raise_()
        self.history_image_1.raise_()
        self.history_image_2.raise_()
        self.history_image_3.raise_()
        self.candidate_box.raise_()
        self.separator.raise_()
        self.history_label.raise_()
        self.tree_label.raise_()
        self.new_parent.raise_()
        self.history_arrow_2.raise_()
        self.history_arrow_1.raise_()
        self.parent_arrows_2.raise_()

        self.retranslateUi(EvolutionGUI)

        QMetaObject.connectSlotsByName(EvolutionGUI)
    # setupUi

    def retranslateUi(self, EvolutionGUI):
        EvolutionGUI.setWindowTitle(QCoreApplication.translate("EvolutionGUI", u"Evolution GUI", None))
        self.parent_image_1.setText("")
        self.parent_image_2.setText("")
        self.child_image.setText("")
        self.history_image_1.setText("")
        self.history_image_2.setText("")
        self.history_image_3.setText("")
        self.candidate_box.setTitle("")
        self.candidate_label.setText(QCoreApplication.translate("EvolutionGUI", u"Choose a mate!", None))
        self.candidate_button_1.setText("")
        self.candidate_button_2.setText("")
        self.candidate_button_3.setText("")
        self.candidate_button_4.setText("")
        self.parent_arrows.setText("")
        self.history_label.setText(QCoreApplication.translate("EvolutionGUI", u"History", None))
        self.tree_label.setText(QCoreApplication.translate("EvolutionGUI", u"Evolutionary Tree", None))
        self.new_parent.setText("")
        self.history_arrow_2.setText("")
        self.history_arrow_1.setText("")
        self.parent_arrows_2.setText("")
    # retranslateUi

